#!/usr/bin/env python3
# questions/*.md と cram-sheet.md をパースして 学習アプリ用の app_data.js を生成する。
# 出力: app_data.js  (const APP_DATA = {...};)
import io, os, re, json, datetime, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SUBJECT_DIRS = {
    "科目1": "questions/subject1-law",
    "科目2": "questions/subject2-terms",
    "科目3": "questions/subject3-practice",
}
CHOICE_RE = re.compile(r"^-?\s*([アイウエ])[\.\．、]\s*(.*)$")
HEAD_RE = re.compile(r"^###\s+(.*)$")
TOPIC_RE = re.compile(r"\[論点[:：]\s*(.*?)\]")
ANS_RE = re.compile(r"正解[:：]\s*([アイウエ・]+)")

def parse_question_file(path, subject, year):
    with io.open(path, encoding="utf-8") as f:
        text = f.read()
    cards = []
    # ### で分割（最初の見出し前は捨てる）
    parts = re.split(r"(?m)^###\s+", text)
    for body in parts[1:]:
        lines = body.split("\n")
        head = lines[0].strip()
        # 末尾の正解一覧テーブル等が ### でない限り混入しないが、念のため
        topic_m = TOPIC_RE.search(head)
        topic = topic_m.group(1).strip() if topic_m else ""
        qno = TOPIC_RE.sub("", head).strip()
        rest = "\n".join(lines[1:])
        # details で問題部と解答部を分ける
        if "<details>" in rest:
            qpart, dpart = rest.split("<details>", 1)
        else:
            qpart, dpart = rest, ""
        # 選択肢と問題文
        choices = []
        stem_lines = []
        for ln in qpart.split("\n"):
            m = CHOICE_RE.match(ln.strip())
            if m:
                choices.append({"k": m.group(1), "text": m.group(2).strip()})
            else:
                if ln.strip():
                    stem_lines.append(ln.strip())
        stem = " ".join(stem_lines).strip()
        # 解答
        ans_m = ANS_RE.search(dpart)
        answer = []
        if ans_m:
            answer = [c for c in ans_m.group(1) if c in "アイウエ"]
        # 解説（details内、正解行以降〜</details>）
        expl = dpart.replace("</details>", "").replace("<summary>解答</summary>", "")
        expl = expl.strip()
        flagged = "正解要確認" in dpart
        ctype = "mcq" if len(choices) >= 2 else "review"
        cards.append({
            "id": f"{year}-{subject}-{len([c for c in cards])+1:02d}",
            "subject": subject, "year": year, "qno": qno, "topic": topic,
            "stem": stem, "choices": choices, "answer": answer,
            "explanation": expl, "type": ctype, "flagged": flagged,
        })
    return cards

def parse_flash_geo():
    """cram-sheet.md の都道府県別リストから flash カードを作る（観光地→県）。"""
    path = os.path.join(ROOT, "cram-sheet.md")
    if not os.path.exists(path):
        return []
    with io.open(path, encoding="utf-8") as f:
        text = f.read()
    cards = []
    # 観光地理 暗記リスト セクションを抜き出す
    m = re.search(r"### 観光地理 暗記リスト.*?(?=\n### )", text, re.S)
    section = m.group(0) if m else ""
    n = 0
    for ln in section.split("\n"):
        bm = re.match(r"^-\s*\*\*(.+?)\*\*[:：]\s*(.+)$", ln.strip())
        if not bm:
            continue
        pref = bm.group(1).strip()
        spots_raw = bm.group(2)
        # ※注記を除去
        spots_raw = re.sub(r"※.*$", "", spots_raw)
        for spot in re.split(r"[／/]", spots_raw):
            spot = spot.strip().strip("。")
            # 括弧補足を残しつつ空は除外
            if not spot or len(spot) < 2:
                continue
            n += 1
            cards.append({
                "id": f"geo-{n:03d}", "subject": "科目3", "year": "地理",
                "qno": f"地理{n}", "topic": "観光地理",
                "stem": f"次の所在地は何県？  {spot}",
                "choices": [], "answer": [], "explanation": f"**{pref}**",
                "type": "flash", "flagged": False, "front": spot, "back": pref,
            })
    return cards

def main():
    all_cards = []
    counts = {}
    for subject, rel in SUBJECT_DIRS.items():
        for path in sorted(glob.glob(os.path.join(ROOT, rel, "R*.md"))):
            year = os.path.splitext(os.path.basename(path))[0]  # R03 等
            cs = parse_question_file(path, subject, year)
            all_cards.extend(cs)
            counts[f"{subject}/{year}"] = len(cs)
    flash = parse_flash_geo()
    all_cards.extend(flash)

    by_type = {}
    by_subject = {}
    for c in all_cards:
        by_type[c["type"]] = by_type.get(c["type"], 0) + 1
        by_subject[c["subject"]] = by_subject.get(c["subject"], 0) + 1

    data = {
        "generatedAt": datetime.date.today().isoformat(),
        "totals": {"all": len(all_cards), "byType": by_type, "bySubject": by_subject},
        "cards": all_cards,
    }
    out = os.path.join(ROOT, "app_data.js")
    with io.open(out, "w", encoding="utf-8") as f:
        f.write("// auto-generated by tools/build_app_data.py — do not edit by hand\n")
        # クラシックスクリプトで window から参照できるよう window に代入する
        # (const/let はグローバルレキシカル束縛になり window.APP_DATA にぶら下がらないため)
        f.write("window.APP_DATA = ")
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    # ログ
    print(json.dumps({
        "out": out, "totalCards": len(all_cards), "flash": len(flash),
        "byType": by_type, "bySubject": by_subject, "perFile": counts,
    }, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
